name: Deploy Apache Web Server to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name  # Set this to your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'    # Path to your web app project; defaults to the repo root
  AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Azure Publish Profile stored as a secret

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Apache
      run: sudo apt-get update && sudo apt-get install -y apache2

    - name: Verify Apache Installation
      run: apache2 -v

    - name: Archive the application
      run: |
        zip -r webapp.zip ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: webapp.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: webapp.zip
        publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
